version: "3"

services:
  bihar-samaj-app:
    container_name: bihar-samaj-app
    build:
      context: .
      args:
        - NEXT_PUBLIC_FRONTEND_URL=${NEXT_PUBLIC_FRONTEND_URL}
        - NEXT_PUBLIC_BACKEND_API=${NEXT_PUBLIC_BACKEND_API}
    restart: always
    ports:
      - "3002:3000" # Mapping to port 3002 to avoid conflict with Grafana (3001)
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_FRONTEND_URL=${NEXT_PUBLIC_FRONTEND_URL}
      - NEXT_PUBLIC_BACKEND_API=${NEXT_PUBLIC_BACKEND_API}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
